### ISSUE TITLE
Why is the vocabulary limited to 30K?

### ISSUE THREAD

**Issue by webeng** [adbrebs/rnn_reader#1]
Why is the vocabulary size is limited to 30K? As far as I know the size of the vocabulary for the CNN is 110K.

I guess decreasing the size of the vocabulary makes the problem easier. How did you choose what words to remove?

Thanks for making the project public 👍

**Comment by adbrebs** [comment]
I re-used the data pipeline of https://github.com/thomasmesnard/DeepMind-Teaching-Machines-to-Read-and-Comprehend. I'm pretty sure that they take the 30K most frequent words and set the rest to unknown.

> I guess decreasing the size of the vocabulary makes the problem easier.

Easier I don't think. It is definitively faster to train (the output layer is 110/30 faster to compute/train) and does not seem to harm performance too much.

**Comment by webeng** [comment]
If it doesn't harm too much then it makes a lot of sense to only reduce the vocabulary.

Thank you.
