### ISSUE TITLE
thnx  - but errors

### ISSUE THREAD

**Issue by avr248** [adbrebs/rnn_reader#3]
(from raccoon import) ValMonitor  = **cannot import name ValMonitor**

(from raccoon.layers.lasagne_extras import)  SequenceSoftmax = 
**cannot import name SequenceSoftmax** 

Please fix the bug because a very interesting project

**Comment by adbrebs** [comment]
I have modified raccoon but haven't updated this repo yet.
To make it work, checkout raccoon to this commit 5174d65e69f7cf7a7b8fd26db6b6eab9a48d0339 (go to the raccoon folder, and type git checkout 5174d65e69f7cf7a7b8fd26db6b6eab9a48d0339).

**Comment by avr248** [comment]
fatal: Not a git repository (or any of the parent directories):

**Comment by adbrebs** [comment]
You need to clone raccoon (git clone https://github.com/adbrebs/raccoon.git and then do the checkout) so that it is a git repo. Don't forget to add raccoon to your python path.

**Comment by avr248** [comment]
thanks very much.
I start training.
